name: CI

on: 
  push:
    branches: [ master ]
  pull_request: 
    branches: [ master ]

jobs:

  build:
  
    runs-on: ubuntu-latest
    
    steps:
    
    - uses: actions/checkout@v2
    
    - name: Run one line script 
      run: echo Hellow World!
      
    - name: rRRUn multiline script
      run: |
        echo first line
        echo seconf line
